In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 00. Pytorch Fundamentals

In [2]:
torch.cuda.is_available()

True

In [3]:
!nvidia-smi

Tue Oct  1 20:25:42 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   62C    P8              10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [4]:
print(torch.__version__)

2.4.1+cu121


## 1 Introdcution to tensors

### Creating tensors
[Pytorch Tensor documentation](https://pytorch.org/docs/stable/tensors.html)

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# Get tensor back as python int
scalar.item()

7

In [8]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
MATRIX[0]

tensor([7, 8])

In [15]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [19]:
TENSOR = torch.tensor([[[1, 3, 3]], [[2, 3, 5]]])
TENSOR

tensor([[[1, 3, 3]],

        [[2, 3, 5]]])

In [20]:
TENSOR.ndim

3

In [21]:
TENSOR.shape

torch.Size([2, 1, 3])

### Random tensors

Random tensors are important becuase the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> uprdate random numbers`

[Pytorch torch.rand Documentation](https://pytorch.org/docs/stable/generated/torch.rand.html)

In [22]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1965, 0.5518, 0.7074, 0.5472],
        [0.5437, 0.0893, 0.8619, 0.1850],
        [0.1139, 0.8423, 0.8359, 0.4611]])

In [23]:
random_tensor.ndim

2

In [24]:
random_tensor.shape

torch.Size([3, 4])

In [25]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [26]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
ones.dtype

torch.float32

In [30]:
# Create a mask tensor where the first column is all 0s
tensor = torch.zeros(3, 4)
tensor[:, 1:] = torch.rand(3, 3)

In [31]:
tensor * random_tensor

tensor([[0.0000, 0.4677, 0.4310, 0.3104],
        [0.0000, 0.0592, 0.8613, 0.1805],
        [0.0000, 0.1962, 0.4632, 0.0206]])

In [32]:
tensor

tensor([[0.0000, 0.8477, 0.6093, 0.5672],
        [0.0000, 0.6630, 0.9993, 0.9758],
        [0.0000, 0.2329, 0.5541, 0.0447]])

### Creating a range of tensors and tensors-like

In [33]:
# Use torch.arange()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [35]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Tensor datatypes are one of the big 3 errors you'll run into with PyTorch & deep learning
1. Tensors not right datatype
2. Tensors not the right shape
3. Tensors not on the right device

In [36]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device="cpu", requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [37]:
float_32_tensor.dtype

torch.float32

In [38]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [39]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3581, 0.2357, 0.7533, 0.4221],
        [0.2838, 0.0974, 0.2138, 0.6556],
        [0.3866, 0.4854, 0.8359, 0.7931]])

In [40]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3581, 0.2357, 0.7533, 0.4221],
        [0.2838, 0.0974, 0.2138, 0.6556],
        [0.3866, 0.4854, 0.8359, 0.7931]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operation include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [41]:
# Create a tensor add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [42]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [43]:
# Subtract the tensor by 10
tensor - 10

tensor([-9, -8, -7])

In [44]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [45]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [46]:
torch.sub(tensor, 10)

tensor([-9, -8, -7])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix Multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. the **inner dimensions** must match
  * `(3, 2) @ (3,2)` won't work
  * `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**
  * `(2,3) @ (3,2)` -> `(2,2)`

In [47]:
# Element-wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [48]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [49]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.18 ms, sys: 841 µs, total: 2.02 ms
Wall time: 1.91 ms


In [50]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 29 µs, sys: 5 µs, total: 34 µs
Wall time: 37.9 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [51]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5,6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's just an alias)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape with transpose

A **transpose** switches the axes or dimensions of a given tensor

In [52]:
tensor_B.T, tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [53]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [54]:
# Create a tensor
x = torch.arange(0, 100, 10)


In [55]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [56]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [57]:
# Find the mean - the torch.mean function requires a tensor of loat32 dataype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [58]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [59]:
# Find the position in the tensor that has the minimal value
x.argmin()

tensor(0)

In [60]:
# Find the position in the tensor that has the maximum value
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor ta defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side-by-side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [61]:
# Let's create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [62]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [63]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [64]:
# Change the view
x = torch.arange(1., 10.)
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [65]:
# Changing z changes x (because a view of a tensor shares the same memory)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [66]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [67]:
# torch.squeeze() - removes all single dimensions from a tensor
x_reshaped.shape

torch.Size([9, 1])

In [68]:
x.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [69]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension (dim)
print(f"Previous target: {x}")
print(f"Previous shape : {x.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape : torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [70]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # height, width, color channels

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shift axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New Shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New Shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [71]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [72]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [73]:
# Lets index on the middle bracket (dim=1)
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [74]:
# Let's index on the most inner bracket (dim=2)
x[0,0,0]

tensor(1)

In [75]:
x[0,1:,1]

tensor([5, 8])

In [76]:
# Get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [77]:
# Index on x to return 9
x[0, 2, 2]

# Index on x to return 3,6,9
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library

And because of this, PyTorch has functionality to interact with it

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor to numpy -> `torch.tensor.numpy()`

In [78]:
# Numpy array to tensor

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [79]:
# Warning: when converting from numpy -> pytorch, pytorch defaults to float64
tensor.type(torch.float32)

tensor([1., 2., 3., 4., 5., 6., 7.])

In [80]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [81]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)

In short, how a neural network learns:

`start with random numbers -> tensor operations -> update random numers to try and make btter representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially, what the random seed does is "flavor" the randomness.

In [82]:
# Create two random tensors

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4354, 0.9233, 0.4949, 0.6655],
        [0.9627, 0.4619, 0.1161, 0.9347],
        [0.3694, 0.0581, 0.1328, 0.8713]])
tensor([[0.9072, 0.3830, 0.9847, 0.6778],
        [0.1943, 0.2871, 0.6213, 0.6243],
        [0.9454, 0.6781, 0.0761, 0.5001]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [83]:
# Let's make some random but reproducible tensors

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch obje t on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything good.

In [84]:
!nvidia-smi

Tue Oct  1 20:30:37 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   52C    P8               9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### Check for GPU access with PyTorch

In [85]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

True

In [86]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [88]:
# Count the numnber of GPUs
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

The reason we want out tensors/models on the GPU is because using a GPU results in faster computations

In [89]:
tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [90]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [91]:
# If a tensor is on the GPU, you cannot convert it to numpy, it must be transferred to CPU first
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## Excercises

In [93]:
x = torch.rand(7, 7, device=device)
x

tensor([[0.9877, 0.1289, 0.5621, 0.5221, 0.7445, 0.5955, 0.9647],
        [0.8979, 0.7730, 0.6681, 0.5462, 0.5071, 0.5882, 0.2555],
        [0.8963, 0.1866, 0.7235, 0.1781, 0.9880, 0.6289, 0.4855],
        [0.7374, 0.2759, 0.9089, 0.6609, 0.6466, 0.3304, 0.0227],
        [0.1423, 0.0653, 0.4122, 0.5799, 0.8216, 0.6970, 0.5771],
        [0.0690, 0.7362, 0.5203, 0.6920, 0.3503, 0.0141, 0.9105],
        [0.1015, 0.2735, 0.7011, 0.1755, 0.7511, 0.0542, 0.9687]],
       device='cuda:0')

In [95]:
x.mm(torch.rand(1, 7, device=device).T)

tensor([[3.0047],
        [2.3139],
        [2.6952],
        [2.1223],
        [1.9225],
        [1.9273],
        [2.1869]], device='cuda:0')